# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the app (if present)
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Deploy to Server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST_IP: ${{ secrets.HOST_IP }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        echo "$PRIVATE_KEY" > private-key.pem
        chmod 600 private-key.pem

        # Fetch and add the server's SSH host key to the known_hosts file
        # ssh-keyscan -H $HOST_IP >> ~/.ssh/known_hosts
          
        # Now copy the files
        scp -i private-key.pem -r * $SSH_USER@$HOST_IP:/home/$SSH_USER/projects/node/hello/

        # SSH into the server and restart the app
        ssh -i private-key.pem $SSH_USER@$HOST_IP << 'EOF'
          cd /home/$SSH_USER/projects/node/hello/
          npm install 
          pm2 restart index.js || pm2 start index.js --name "node-app"
        EOF
